amaggiulli/QLNet

- QLNet/Termstructures/Yield/DiscountCurve.cs
- QLNet/Termstructures/Yield/ForwardCurve.cs
- QLNet/Termstructures/Yield/ZeroCurve.cs
Updates the zero, forward and discount interpolated curves to be in line with the latest QuantLib code.
Mainly adds more constructors.
Adds compounding and frequency for zero curves.
> Updated interpolated curves

- QLNet/Math/PrimeNumbers.cs
> Fix prime number implementation.

- QLNet/Time/Schedule.cs
- Test/T_Schedule.cs
Add schedule tests and fix some Schedule constructor issues.
> Add schedule tests

- Test/T_Bonds.cs
Add bond test for South African R2048 which requires Schedule from custom Date vector.
> Add R2048 ZA bond test

- QLNet/Math/Interpolations/bilinearinterpolation.cs
- QLNet/Math/Interpolations/interpolation2d.cs
- QLNet/QLNet.csproj
- QLNet/Termstructures/Volatility/equityfx/BlackVarianceSurface.cs
Initial implementation. I don't have any test cases, so not sure whether it's buggy.
> BlackVarianceSurface implementation

- QLNet/Settings.cs
- Test/T_AsianOptions.cs
- Test/T_Bonds.cs
- Test/T_CashFlows.cs
- Test/T_CreditDefaultSwap.cs
- Test/T_DigitalOption.cs
- Test/T_DividendOption.cs
- Test/T_HestonModel.cs
- Test/T_Inflation.cs
This fixes the tests in parallel mode.
I had to reindent some of the test files, because they were such a mess of spaces, tabs and inconsistent indentation. I did the reformatting in a separate commit, so the actual fix is viewable in its own commit.
> Disposable SavedSettings

- QLNet/Math/Interpolations/CubicInterpolation.cs
Port https://github.com/lballabio/quantlib/commit/ae3846097158d363633bd7305291b882f2f24765
> Implemented Lagrange boundary condition for cubic interpolation

- QLNet/QLNet.csproj
> Following the convention of Quant lib, default is to allow negative rates

- QLNet/Termstructures/Yield/Ratehelpers.cs
Initialise empty convexity adjustment if null
> Initialise empty convexity adjustment if null

- QLNet/Termstructures/Yield/DiscountCurve.cs
- QLNet/Termstructures/Yield/ForwardCurve.cs
Reverts amaggiulli/qlnet#107 , need to be merged on develop
> Revert "typos"

- QLNet/Math/Interpolations/BicubicSplineInterpolation.cs
…ace like BlackVarianceSurface can set it to interpolation
> made Bicubic inherited from IInterpolationFactory2D, so that vol surf

- QLNet/Pricingengines/Bond/TreeCallableBondEngine.cs
Just add ".link" resolve the issue and the CallableBond Example runs fine.
> Cast issue in TreeCallableBondEngine

- Examples/BermudanSwaption/BermudanSwaption.cs
Not sure this is the expected results, but at least the example is running
> Issue with times in the TimeGrid

- QLNet/Indexes/InflationIndex.cs
Port of 
https://github.com/lballabio/QuantLib/pull/224/commits/37a3f312d454ba0baa67f3f1a753606beb4450fd
> Fix inflation reference period interpolation

- QLNet/QLNet.csproj
- QLNet/Termstructures/Volatility/equityfx/HestonBlackVolSurface.cs
Still need to find a unit test. But initial testing looks good.
> Implement HestonBlackVolSurface

- src/QLNet/Utils.cs
- tests/QLNet.Tests/T_Vector.cs
Don't implement ICloneable for NET45 (fix boolean logic)
Don't reference ICloneable by namespace
> ICloneable references

- src/QLNet.Old/QLNet.Old.csproj
- src/QLNet/Math/Interpolations/SviInterpolation.cs
- src/QLNet/Termstructures/Volatility/Svi.cs
- src/QLNet/Termstructures/Volatility/SviInterpolatedSmileSection.cs
- src/QLNet/Termstructures/Volatility/SviSmileSection.cs
- tests/QLNet.Tests.Old/QLNet.Tests.Old.csproj
- tests/QLNet.Tests/T_SVI.cs
Added a test based on P. Caspers work (https://sourceforge.net/p/quantlib/mailman/message/32701703/)
> Port SVI Interpolation + SmileSection from QuantLib

- src/QLNet/Instruments/forward.cs
Allow to override in child class
> Put forwardValue method as virtual

- src/QLNet/Instruments/Swaption.cs
- src/QLNet/Pricingengines/swaption/blackswaptionengine.cs
- src/QLNet/Termstructures/Volatility/swaption/swaptionconstantvol.cs
- src/QLNet/Termstructures/voltermstructure.cs
Take into account the Bachelier method for normal volatility.
> Add normal vol to swaption

- src/QLNet/Instruments/MakeCms.cs
> Add cap/floors setters for CMS and Ibor legs

- src/QLNet/Termstructures/Volatility/equityfx/FixedLocalVolSurface.cs
- src/QLNet/Termstructures/Volatility/equityfx/NoExceptLocalVolSurface.cs
- src/QLNet/processes/BlackScholesProcess.cs
Fixed Local Vol + No Except Local Vol
I also added a constructor for Generalized BS Process not existing in the original Quantlib
> Quantlib port

- src/QLNet.Old/QLNet.Old.csproj
> Projet file fix

- src/QLNet/Indexes/Swapindex.cs
Call to base constructor is missing
> Bug fix swap index

- src/QLNet/Math/Interpolations/XABRInterpolation.cs
This way we can add Constraint on parameters by objects derived from XABRConstraint.
> Allow constraint on XABR interpolation

- src/QLNet/Indexes/Indexmanager.cs
<hr />
Adds a small helper method `tryGetHistory(..)` to simplify some `IndexManager` lookups. It's based on the fairly common `Try...` pattern in .NET. Will add unit tests if required, but I think this is small enough to omit them.
<hr />
Be kind to code reviewers, please …
> Add helper method IndexManager.tryGetHistory

- README.md
Very basic updates to get the badges updated and working correctly
> Updating badges in README.md

- src/QLNet/Patterns/WeakEventSource.cs
- src/QLNet/Settings.cs
> Being able to clear settings Observers

- src/QLNet/Instruments/Makeswaption.cs
- src/QLNet/Instruments/Swaption.cs
- src/QLNet/Pricingengines/swaption/BlackSwaptionEngine.cs
- src/QLNet/Pricingengines/swaption/JamshidianSwaptionEngine.cs
- src/QLNet/Pricingengines/swaption/TreeSwaptionEngine.cs
- src/QLNet/legacy/libormarketmodels/LfmSwaptionEngine.cs
- tests/QLNet.Tests/T_Swaption.cs
This PR add the new methodology for swaption pricing.
Ported from Quantlib.
> Collateralized Cash Swaption

- src/QLNet/Instruments/Bonds/AmortizingFixedRateBond.cs
Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)
owners to license your work under the terms of the [BSD3 …
> Assignment was made twice.

- src/QLNet/Time/Date.cs
This pull request closes issue #233 
The only change is trivial, so I didn't create tests and skipped that part in guidelines. All other checkboxes I mentally checked :)
Interesting fact - seems that this change can speedup QLNet at all and `TimeSeries<T>` in particular.
> Date.GetHashCode() implemented (closes #233)

- src/QLNet/processes/HestonProcess.cs
Fix needed in future tests update
> [Heston process] Fix Broadie-Kaya exact scheme

- src/QLNet/Math/ODE/AdaptiveRungeKutta.cs
Lists need to be initialized or it will results in an error.
> Adaptive Runge Kutta

- src/QLNet.Old/QLNet.Old.csproj
- src/QLNet/Methods/Finitedifferences/Meshers/FdmBlackScholesMesher.cs
- src/QLNet/Methods/Finitedifferences/Operators/FdmBlackScholesOp.cs
- src/QLNet/Methods/Finitedifferences/Solvers/FdmBlackScholesSolver.cs
- src/QLNet/Methods/Finitedifferences/Utilities/FdmDividendHandler.cs
- src/QLNet/Methods/Finitedifferences/Utilities/FdmQuantoHelper.cs
- src/QLNet/Pricingengines/barrier/FdBlackScholesBarrierEngine.cs
- src/QLNet/Pricingengines/barrier/FdBlackScholesRebateEngine.cs
- src/QLNet/Pricingengines/vanilla/FdBlackScholesVanillaEngine.cs
- src/QLNet/Termstructures/Yield/QuantoTermStructure.cs
Add Quanto Term Structure class to QLNet Project.
Dividends are also better managed under finite difference method via Black-Scholes model.
I updated the Old Project File too, including an update of filename to reflect the updated convention.
> Add Quanto Term Structure

- src/QLNet/Time/Date.cs
Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)
owners to license your work under the terms of the [BSD3 …
> Add utility Date.ToDateTime() method

- samples/BermudanSwaption/BermudanSwaption.csproj
- samples/Bonds/Bonds.csproj
- samples/CVAIRS/CVAIRS.csproj
- samples/CallableBonds/CallableBonds.csproj
- samples/ConvertibleBonds/ConvertibleBonds.csproj
- samples/EquityOption/EquityOption.csproj
- samples/FRA/FRA.csproj
- samples/FittedBondCurve/FittedBondCurve.csproj
- samples/Repo/Repo.csproj
- samples/Swap/Swap.csproj
Updated netcore2.2 to net5.0 framework for sample projects.
> Target Net5.0 Framework in samples too.

- src/QLNet/Pricingengines/asian/McDiscreteAsianEngine.cs
- src/QLNet/Pricingengines/asian/Mc_Discr_Arith_Av_Price.cs
Hello there, thanks for your hard work! 🙂 
I took the liberty of fixing what I believe to be two minor bugs:
1. Fixed a case where `.Add` was called on an `InitializedList`
2. Fixed a call to `value(IPath)` which seemed to bypass the correct implementation
Let me know if there's something I should add to this.
Thanks again.
> Fix a few things

- src/QLNet/Time/Calendars/Cyprus.cs
- src/QLNet/Time/Calendars/Greece.cs
Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)
owners to license your work under the terms of the [BSD3 …
> Greece and Cyprus Calendars

- appveyor.yml
- src/QLNet/QLNet.csproj
- tests/QLNet.Tests/QLNet.Tests.csproj
Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)
owners to license your work under the terms of the [BSD3 …
> Update to .NET 8 - Closes #283

- src/QLNet/Instruments/Futures.cs
- src/QLNet/Termstructures/Yield/Ratehelpers.cs
This is trnasfered from the C++ code: https://github.com/lballabio/QuantLib/pull/1915
This allows passing custom future dates. Ref: Closes #1855: https://github.com/lballabio/QuantLib/issues/1855
owners to license your work under the terms of the [BSD3 License](https://github.com/amaggiulli/qlnet/blob/develop/LICENSE).
> Added Futures Type - Custom;
